openapi: 3.0.0
info:
  title: 'Subscriber API'
  version: '1.0'
paths:
  /api/subscribers:
    get:
      summary: 'Get list of subscribers'
      operationId: 7a4ec4a0bed9cb1bb0f252aa5fde1ac4
      responses:
        200:
          description: 'List of subscribers'
    post:
      summary: 'Create a new subscriber'
      operationId: cdbdfb57ab947416e0ecf36c82ed29e8
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
                - name
                - email
              properties:
                name:
                  type: string
                  example: 'John Doe'
                email:
                  type: string
                  format: email
                  example: john.doe@example.com
              type: object
      responses:
        201:
          description: 'Subscriber created'
  '/api/subscribers/{id}':
    get:
      summary: 'Get a subscriber by ID'
      operationId: cb2ebc56c624405a54492302dbb13aee
      parameters:
        -
          name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: 'Subscriber found'
        404:
          description: 'Subscriber not found'
    put:
      summary: 'Update a subscriber by ID'
      operationId: f7edc93245402315d3f961da3ec023a6
      parameters:
        -
          name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
                - name
                - email
              properties:
                name:
                  type: string
                  example: 'John Updated'
                email:
                  type: string
                  format: email
                  example: john.updated@example.com
              type: object
      responses:
        200:
          description: 'Subscriber updated'
    delete:
      summary: 'Delete a subscriber by ID'
      operationId: d5182899aaacc15b1b2a04f7808dd746
      parameters:
        -
          name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        204:
          description: 'Subscriber deleted'
