version: "3.1"
services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-laravel
      - node-express
      - python-fastapi

  node-express:
    image: node:alpine
    environment:
      NODE_ENV: production
    working_dir: /home/app
    restart: always
    volumes:
      - ./node-express:/home/app
    command: ["node", "index.js"]

  php-laravel:
    build: ./php-laravel
    # image: webdevops/php-apache-dev:8.2
    volumes:
      - ./php-laravel:/app
    ports:
      - "8002:80"
    environment:
      WEB_DOCUMENT_ROOT: /app/public

  python-fastapi:
    build: ./python-fastapi
    ports:
      - "8003:8000"
    volumes:
      - ./python-fastapi:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
